### ISSUE TITLE
Ability to encrypt all files in folder

### ISSUE THREAD

**Issue by CertainLach** [jamessan/vim-gnupg#101]
I want to use this for all files (with any extenstion) within a specified dir, how can i do that?

**Comment by jamessan** [comment]
You want to change `g:GnuPGFilePattern` to match any file under that directory.  If that's supposed to be in addition to the normal extension-based matching, then you can use a comma-separated value of the dir-specific pattern and extension-based pattern.

For example:

```vim
let g:GPGFilePattern = '*.{gpg,asc,pgp},/secret/directory/*'
```
