### ISSUE TITLE
Error While Opening File - Unknown Function: gnupg#init

### ISSUE THREAD

**Issue by brandon1024** [jamessan/vim-gnupg#102]
I tried playing around with this plugin for a while, but I couldn't seem to figure out this error. Whenever I open a `.asc`, `.gpg`, or `.pgp` file in Vim, I get the following error:

```
Error detected while processing BufReadCmd Autocommands for "*.{gpg, asc, pgp}":
E117: Unknown function: gnupg#init
```

I first tried this on WSL on my work machine but no luck, then tried on my Arch machine at home with no luck there either. I don't think it's a misconfiguration of the plugin, but I could be wrong. I tried stripping down my .vimrc to the bare minimum to see if maybe plugins were clashing, but that was not the case.

I really want to get this working, I use GPG often and this plugin would simplify this so much. I'm going to play around with it for a bit longer, but any help would be appreciated.

### Configuration
```
$ echo $GPG_TTY
/dev/pts/4

$ which gpg
/usr/bin/gpg

$ gpg --version
gpg (GnuPG) 2.2.12
libgcrypt 1.8.4
[...]
Home: /home/brandon/.gnupg

$ cat .vimrc
" Armor Files
let g:GPGPreferArmor=1
" Set the default option
let g:GPGDefaultRecipients=["brandon1024.br@gmail.com"]
```

### Screenshots
![image](https://user-images.githubusercontent.com/22732449/59551305-0247ed00-8f4e-11e9-9343-bbb408bf7afb.png)

**Comment by brandon1024** [comment]
Figured it out.. I didn't correctly install the plugin. For those who stumble across this issue in the future, do the following:

```
$ cd ~/.vim
$ git clone git@github.com:jamessan/vim-gnupg.git
$ mv vim-gnupg/* .
```

**Comment by jamessan** [comment]
A better option would be using [pathogen](https://github.com/tpope/vim-pathogen) or Vim's [package](https://vimhelp.org/repeat.txt.html#packages) support to contain the plugin in its own directory.

For example, with the package support:

```
$ mkdir -p ~/.vim/pack/bundle/start
$ cd ~/.vim/pack/bundle/start
$ git clone git@github.com:jamessan/vim-gnupg.git
```

Vim will find and load everything on its own, without mixing the files with others.

---
I see that the install instructions in the README are outdated now that there's more than just a single file in `plugin/`.  I'll update those.

**Comment by brandon1024** [comment]
@jamessan You're right. I don't have any experience with those, I think it's about time hehe.

Good call, I found the install instructions a bit confusing.
