### ISSUE TITLE
contents of main buffer are parsed as recipients

### ISSUE THREAD

**Issue by ThomasAH** [jamessan/vim-gnupg#104]
As indicated in other issues I had problems with git master, which did not exist in v2.6.1.
I just tested again with 6219a5a0d70dbc10c5e70289a2c400d6d8b62762 and found the following:

1. `vim test.gpg`
1. if the file already existed, use `:GPGEditRecipients` to open the recipients list
1. close the recipients list (optionally add or remove recipients)
1. change the text of the main buffer to just `com` (or anything else that has multiple matches in your keyring), optionally add additional lines with `org`, `debian` (or whatever has multiple matches in your keyring)
1. save the file

Now for each line of the main buffer that matches multiple keys in your keyring, gnupg.vim asks to select the correct recipient.
(the file does not get encrypted to these recipients though)

**Comment by leahneukirchen** [comment]
This still happens on 2.7. Luckily the lines are shell escaped, but **this leaks secrets to other users of the system that use ps or top**.

**Comment by jamessan** [comment]
I think I see what's going on.  I should have a fixed version out today or tomorrow.  I'll ping you on the PR to verify it fixes your uses.
