### ISSUE TITLE
Already encrypted file "File is not encrypted, all GPG functions disabled!"

### ISSUE THREAD

**Issue by PipeItToDevNull** [jamessan/vim-gnupg#109]
Opening a pre-encrypted file in vim on windows installed via scoop

```
echo "testificate" > test.txt
gpg -s .\test.txt 
vim .\test.txt.gpg -V
```
`File is not encrypted, all GPG functions disabled!`

I am able to open a blank file as `.gpg` or `.asc`, encrypt using the vim-gnupg prompts and continue to open that file just fine but any existing encrypted files cannot be opened.

**Comment by penguin359** [comment]
It looks like you tried to create a signed file, not encrypted, and opened it with vim. Try using gpg -e if you want an encrypted file.

**Comment by PipeItToDevNull** [comment]
You are correct, I am an idiot
