### ISSUE TITLE
Improve handling of viminfo unsetting

### ISSUE THREAD

**Issue by blueyed** [jamessan/vim-gnupg#11]
When opening an encrypted file in the middle of a Vim session, the plugins behavior of unsetting viminfo is nasty, because you will lose valuable information from the other buffers / your whole session.

The main concern appears to be that e.g. no registers with sensible data are being stored?! What else is affected?

It might make sense to have a setting to disable unsetting "viminfo" altogether, or have a warning / dialog which asks the user about how to handle it.

Either way, the old value of 'viminfo' could get stored in a global var, making it easier to re-enable it.

**Comment by jamessan** [comment]
I haven't been able to come up with a reasonable solution to this issue.  I understand the desire to maintain information for non-encrypted files, but there doesn't seem to currently be a way to do that without also leaking information about the encrypted files.  At least not from the plugin side of things.

If Vim were changed such that `'viminfo'` could be set on a per-buffer basis or there were some other means for excluding buffers without outright disabling `'viminfo'`, I would be glad to take advantage of that.

**Comment by BohrShaw** [comment]
@jamessan So generally, restoring 'viminfo' is not viable. But how about providing an option to not reset 'viminfo' in the first place?

As you suggested, I would edit encrypted files in a dedicated Vim instance. But editing in the normal current Vim instance still has its user cases:

- The user is not concerned with the contents of encrypted file.
- It's a small quick edit coupled with the current session, and the user is careful enough.

**Comment by jamessan** [comment]
If the user is not concerned with the contents of the encrypted file, then why is it encrypted? :) If something changes on the Vim side, I'll be glad to revisit this issue, but until then I think it's an acceptable trade off.  I will bring up the ideas with Bram to try and get some traction on a viable change here.

**Comment by BohrShaw** [comment]
> If the user is not concerned with the contents of the encrypted file, then why is it encrypted?
Oops, I meant to say: The user may be unconcerned that the file is _locally_ unencrypted.

It's fine to leave it as is for now. The user can always restore 'viminfo' with a handy auto-command.
