### ISSUE TITLE
Need to type passphrase on every :w ?

### ISSUE THREAD

**Issue by eater** [jamessan/vim-gnupg#118]
My passphrase is cached when I decrypt a .gpg file, but every time I write that file I have to type it in again. Is there any caching possible for **en**crypting?

**Comment by jamessan** [comment]
That's entirely up to gpg.  The plugin doesn't see your passphrase.

**Comment by eater** [comment]
I do know that it's up to gpg -- I am just wondering if there is a way to configure gpg for this that I am missing, or whether this is a known inconvenience that I should stop trying to figure out. Thanks.

**Comment by jamessan** [comment]
If you're using symmetric (passphrase) encryption, no it's not cached. If you're using asymmetric encryption, then gpg-agent/pinentry has a ttl for how long the key is cached.

**Comment by eater** [comment]
Thanks, that's good to know!
