### ISSUE TITLE
Start vim without to create a buffer to edit recipients (GPGEditRecipients)

### ISSUE THREAD

**Issue by johackim** [jamessan/vim-gnupg#120]
Hello,

Can we use this plugin without have to create a buffer edit recipients each time we start vim ?

When I start vim :

```bash
vim test.txt.gpg
```

A buffer is created with the GPGEditRecipients command.

I already added this parameter : `let g:GPGDefaultRecipients=["johackim"]`

Thanks for this plugin !

**Comment by jamessan** [comment]
I prefer to be explicit about who the buffer will be encrypted to.  Closing the window acknowledges the recipients, so it's pretty quick if you're fine with the default.
