### ISSUE TITLE
Add the ability to use age?

### ISSUE THREAD

**Issue by vext01** [jamessan/vim-gnupg#122]
Hi,

I've been using your fantastic plugin for editing gpg encrypted files for some years now. Thank you!

I've recently ditched gpg, and now use [age](https://github.com/FiloSottile/age). I wonder if there is scope to add support for age to your plugin?

Thanks

**Comment by jamessan** [comment]
The plugin is currently very tailored towards gpg.  Changing to support age would require a pretty heavy refactoring to be a general "encryption" plugin that supports different backends.

That's a bit more than I can take on right now.  My priority for any big chunk of time with this plugin is to get it working properly with tty pinentry/neovim.

**Comment by vext01** [comment]
No worries. Sounds like we should close this then?
