### ISSUE TITLE
[Bug] Neovim compatability of vim-gnupg with pinentry-mac - only get encrypted file

### ISSUE THREAD

**Issue by wakatara** [jamessan/vim-gnupg#124]
*[re-submitted as new ticket by request of maintainer]*

I am using pinentry-mac with:

gpg (GnuPG) 2.3.4
libgcrypt 1.10.1
neovim 0.6.1
and OSX 12.3 on an M1 chipped Mac
(and homebrew installed as native M1 so gpg and pinentry-mac both native)
vim 8.2 (works)
using Plug to install latest version of vim-gnupg plugin.

I am simply trying to transparently decrypt a file in neovim in order to get a markdown journalling program working (think, like org-journal with transparent encryption in emacs). 

I get prompted for the pinetry-mac password for the system unlock (as is saved in the keychain) but I only get the encrypted text in neovim on success.

I also installed the plugin in straight up vim. It works fine in classic vim with the same setup (😍) but since I have a number of neovim-only plugins (particularly telekasten), I need it to work in neovim. 

Could someone point me at how I can help diagnose the issue considering its obviously related to neovim and the plugin since I can confirm it working with old-school vim 8.2.

thanks!

**Comment by jamessan** [comment]
`nvim -V3gpg.log foo.gpg` and then post the log.

**Comment by wakatara** [comment]
@jamessan 

Hmmm... did not know you could do that. Note: that the file gets a prompt asked for in order to decrypt it, it's just the output looks like the encoded file rather than decrypted (and as mentioned, the vim classic plugin works fine with this).

log attached. I am very curious as to what you find in it as I personally took a look but did not glean much from it.
(note on a separate issue since it shows up in the logs, I have a small issue with my navigator config and its default cfg, but it appears completely unrelated.)

[gpg.log](https://github.com/jamessan/vim-gnupg/files/8406350/gpg.log)

**Comment by jamessan** [comment]
I don't see the gnupg plugin running at all.  Does `:autocmd GnuPG` show any autocmds setup?

**Comment by wakatara** [comment]
So, rather strangely, I did a :PlugUpdate last night and I am unsure if there was some sort of conflict with another plugin (I also added and removed some plugins), but the I just tried decrypting the main journal flie and it worked flawlessly this time. 

Copied the main file of note someplace else for safety, made some changes, saved and could reopen it and decrypts and saves changes transparently and works just as it did with vim classic this time, so I am unsure what was going on before, but it seems to be working fine now. (so, very sorry if I wasted your time if it was something I happened to do with my config, though do not think I have changed anything major that should have affected vim-gnupg.).

On the other hand, it is working (even if not showing up in logs), so that's a *huge* plus from my perspective. Thank you for taking a look at this problem! 
(and once again, for all your hard work on the plugin itself. I am still super happy to see this in the ecosystem... =] ). 

ciao!

**Comment by wakatara** [comment]
For the record, this is the output of the `:autocommand GnuPG` on my nvim config.

```
--- Autocommands ---                                                                                                                                                     
GnuPG  BufReadCmd                                                                                                                                                        
    *.{gpg,asc,pgp}                                                                                                                                                      
              call gnupg#init(1) | call gnupg#decrypt(1)                                                                                                                 
GnuPG  BufWriteCmd                                                                                                                                                       
    *.{gpg,asc,pgp}                                                                                                                                                      
              if !exists('b:GPGCorrespondingTo') | call gnupg#init(0) | call gnupg#encrypt() | endif                                                                     
GnuPG  FileReadCmd                                                                                                                                                       
    *.{gpg,asc,pgp}                                                                                                                                                      
              call gnupg#init(0) | call gnupg#decrypt(0)                                                                                                                 
GnuPG  FileWriteCmd                                                                                                                                                      
    *.{gpg,asc,pgp}                                                                                                                                                      
              if !exists('b:GPGCorrespondingTo') | call gnupg#init(0) | call gnupg#encrypt() | endif  
```

**Comment by benoror** [comment]
I created a plugin repository, contributions welcomed! https://github.com/benoror/gpg.nvim
