### ISSUE TITLE
Error detected while processing BufReadCmd Autocommands for "*.{gpg,asc,pgp}"

### ISSUE THREAD

**Issue by rubin55** [jamessan/vim-gnupg#126]
Lately I'm getting this error when opening an encrypted .gpg text file:

```
Error detected while processing BufReadCmd Autocommands for "*.{gpg,asc,pgp}"..function gnupg#init[115]..<SNR>55_GPGSyst
em[11]..<SNR>55_GPGPostCmd:
line    8:
E530: Cannot change 'term' in the GUI
E530: Cannot change 'term' in the GUI
E530: Cannot change 'term' in the GUI
E530: Cannot change 'term' in the GUI
```

I'm using `gvim`.

**Comment by jamessan** [comment]
Did you recently switch to gvim?  That error has been in Vim for a long time, as has the code in the plugin which is triggering it.

I can push a fix for this.

**Comment by rubin55** [comment]
Fix would be much appreciated! I switched to GVim about 4 months ago, the errors have indeed showed up consistently since I started using GVim.
