### ISSUE TITLE
Clipboard support since bd3ebdf

### ISSUE THREAD

**Issue by hardenedapple** [jamessan/vim-gnupg#22]
For me, when using console vim, the + and \* registers don't show up with :reg or work with other programs with the "let &term = &term" line, added in commit bd3ebdf.

So copying text from external programs into the buffer, and vice versa doesn't work, the registers just act like the other character registers.

I don't have a clue why.

**Comment by jamessan** [comment]
As of [7.4.959](https://github.com/vim/vim/releases/tag/v7.4.959), interaction with the clipboard should work again.
