### ISSUE TITLE
Browse a tarball after decrypting it

### ISSUE THREAD

**Issue by windowsrefund** [jamessan/vim-gnupg#24]
Vim can browse the directory tree of a tarball so I can't help but wonder how cool it would be to end up with that scenario given the following:

$ vim foo.tar.gz.asc

At this time, the file is decrypted but then vim errors on the resulting foo.tar.gz

Error: Could not read uncompressed file

**Comment by jamessan** [comment]
From a quick look, it seems there are a couple things that need to happen to get this working.

- [ ] Add triggering of `BufReadPre`.  Should probably add triggering of `FileReadPre` while in this area.
- [ ] Preserve the legitimate values of `'[`/`']` in GPGBufReadPost so the gzip plugin has the right line range to work on.  Experimenting shows that that `:lockmarks` isn't working when added to the [1delete](https://github.com/jamessan/vim-gnupg/blob/master/plugin/gnupg.vim#L560) command triggered in `GPGBufReadPost`.
- [ ] Add triggering of `FileReadPost`.

Once those are done, the ground work should be available to browse the tar file.  Not sure how well it will work in reality, but if nothing else the plugin will behave more in line with normal Vim when reading a file.

The `FileRead*` events aren't specifically required, but it would round out the partial support that was added in 9de82fa.

**Comment by jamessan** [comment]
Well, I've pushed those changes but that's still not working.  I'll have to dig into it some more another time.

**Comment by jamessan** [comment]
Ah, the remaining problem is actually a bug in the gzip plugin.  It needs to `setlocal noeol` along with the existing `setlocal binary` in its `BufReadPre` autocmd.  I'll send a note to the maintainer.

Closing this issue since all the changes required in vim-gnupg have been made.

**Comment by windowsrefund** [comment]
Awesome. Thanks for everything
