### ISSUE TITLE
Incompatible with bogado/file-line

### ISSUE THREAD

**Issue by towolf** [jamessan/vim-gnupg#25]
Recently vm-gnupg stopped working properly. It loads an encrypted  .gpg file and after flashing the clear-text briefly it shows a buffer of scrambled bytes.

I disabled my other bundles one-by-one and found that when both jamessan/vim-gnupg and bogado/file-line are active this issue occurs. I filed this issue there as well.

Another issue is that when loading a .gpg file all syntax highlighting and colors are disabled. Is that intentional?

**Comment by towolf** [comment]
Found another issue that hints at the incompatibility.

bogado/file-line#38

**Comment by jamessan** [comment]
Based on bogado/file-line#37, it seems like this is definitely in file-line's space.  Closing.

**Comment by towolf** [comment]
Ok, fair enough.

What about the colors and syntax highlighting? This is disabled even when only vim-gnupg is loaded.

**Comment by jamessan** [comment]
Please open a separate issue with some more details.
