### ISSUE TITLE
Somehow disable syntax highlighting and colors

### ISSUE THREAD

**Issue by towolf** [jamessan/vim-gnupg#26]
![Imgur](http://i.imgur.com/9kolNKY.gif)

**Comment by towolf** [comment]
Messed up a bit in the gif.

The point is when editing .gpg files the colors are lost.

**Comment by jamessan** [comment]
Can you post the output of `:scriptnames` in both situations?

**Comment by jamessan** [comment]
Without more information, I'm going to have to close this report.  There's nothing in gnupg.vim that should affect this.

**Comment by towolf** [comment]
Sorry, forgot about this issue

`:scriptnames` with `vim-gnupg`


```
  1: /usr/share/vim/vimrc
  2: /usr/share/vim/vim74/debian.vim
  3: /usr/share/vim/vim74/syntax/syntax.vim
  4: /usr/share/vim/vim74/syntax/synload.vim
  5: /usr/share/vim/vim74/syntax/syncolor.vim
  6: /usr/share/vim/vim74/filetype.vim
  7: ~/.vimrc
  8: /usr/share/vim/vim74/syntax/nosyntax.vim
  9: ~/.vim/colors/lilydjwg_dark.vim
 10: /usr/share/vim/vim74/ftoff.vim
 11: ~/src/txt/vundle/autoload/vundle.vim
 12: ~/src/txt/vundle/autoload/vundle/config.vim
 13: /usr/share/vim/vim74/ftplugin.vim
 14: /usr/share/vim/vim74/indent.vim
 15: ~/src/txt/vim-gnupg/plugin/gnupg.vim
 16: /usr/share/vim/vim74/plugin/getscriptPlugin.vim
 17: /usr/share/vim/vim74/plugin/gzip.vim
 18: /usr/share/vim/vim74/plugin/matchparen.vim
 19: /usr/share/vim/vim74/plugin/netrwPlugin.vim
 20: /usr/share/vim/vim74/plugin/rrhelper.vim
 21: /usr/share/vim/vim74/plugin/spellfile.vim
 22: /usr/share/vim/vim74/plugin/tarPlugin.vim
 23: /usr/share/vim/vim74/plugin/tohtml.vim
 24: /usr/share/vim/vim74/plugin/vimballPlugin.vim
 25: /usr/share/vim/vim74/plugin/zipPlugin.vim
 26: /usr/share/vim/vim74/scripts.vim
```

`:scriptnames` without

```
  1: /usr/share/vim/vimrc
  2: /usr/share/vim/vim74/debian.vim
  3: /usr/share/vim/vim74/syntax/syntax.vim
  4: /usr/share/vim/vim74/syntax/synload.vim
  5: /usr/share/vim/vim74/syntax/syncolor.vim
  6: /usr/share/vim/vim74/filetype.vim
  7: ~/.vimrc
  8: /usr/share/vim/vim74/syntax/nosyntax.vim
  9: ~/.vim/colors/lilydjwg_dark.vim
 10: /usr/share/vim/vim74/ftoff.vim
 11: ~/src/txt/vundle/autoload/vundle.vim
 12: ~/src/txt/vundle/autoload/vundle/config.vim
 13: /usr/share/vim/vim74/ftplugin.vim
 14: /usr/share/vim/vim74/indent.vim
 15: /usr/share/vim/vim74/plugin/getscriptPlugin.vim
 16: /usr/share/vim/vim74/plugin/gzip.vim
 17: /usr/share/vim/vim74/plugin/matchparen.vim
 18: /usr/share/vim/vim74/plugin/netrwPlugin.vim
 19: /usr/share/vim/vim74/plugin/rrhelper.vim
 20: /usr/share/vim/vim74/plugin/spellfile.vim
 21: /usr/share/vim/vim74/plugin/tarPlugin.vim
 22: /usr/share/vim/vim74/plugin/tohtml.vim
 23: /usr/share/vim/vim74/plugin/vimballPlugin.vim
 24: /usr/share/vim/vim74/plugin/zipPlugin.vim
 25: /usr/share/vim/vim74/scripts.vim
```

difference is only `~/src/txt/vim-gnupg/plugin/gnupg.vim`

When vim is loaded with blank color theme, when editing a `.gpg` file I can issue `set t_Co=256` to re-enable the theme. 

Dunno why this is necessary for vim-gnupg. Putting this at the bottom of .vimrc is not enough.

**Comment by jamessan** [comment]
Ah, are you manually setting `t_Co` in your vimrc?

**Comment by towolf** [comment]
Yes, and have been for a long time.

**Comment by jamessan** [comment]
Yeah, that's the problem.  You shouldn't be setting that manually.  Instead, you should configure your terminal so that Vim is able to figure out that it supports 256 colors automatically.

Due to odd interactions with pinentry, the plugin has to re-set the `'term'` option, which causes `t_Co` to be set back to whatever Vim detects the terminal supports.

**Comment by jamessan** [comment]
If you do decide to continue setting it manually, then you should do so from the `TermChanged` autocmd

    au TermChanged * set t_Co=256

**Comment by towolf** [comment]
I’m using gnome-terminal. I have this in my .bashrc

```
if [ "$COLORTERM" == "gnome-terminal" ]; then
  export TERM=xterm-256color
fi
```

 but for some reason gnome-terminal stopped exporting the `COLORTERM` variable. Maybe that is what made it to stop working. 

My `TERM` is now just `xterm`. If I manually set `xterm-256color` then even `vim-gnupg` works again.

Will investigate this. Thanks.

**Comment by towolf** [comment]
This solves it instead:

```
if [ "${VTE_VERSION:-0}" -ge 3405 ]; then
  export TERM=xterm-256color
fi
???

**Comment by towolf** [comment]
It’s a [12 year old bug that is still going strong](https://bugzilla.gnome.org/show_bug.cgi?id=115750)

**Comment by jamessan** [comment]
Yeah.  Comment # 3 is referring to me. :) I think one of the latest gnome-terminal releases, they finally allow you to set $TERM without having to recompile.  I don't use gnome-terminal, only support Vim users that get frustrated by it, so I don't recall the specifics.  It may be some gconf setting.
