### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by wikimatze** [jamessan/vim-gnupg#27]
Hi James, can you make a new release tag? Thanks for this great plugin.

Bests Matthias

**Comment by danielcotton** [comment]
I think this would be a good idea. 2.5 has been around for nearly three years (http://www.vim.org/scripts/script.php?script_id=3645)[according to vim.org].

**Comment by wikimatze** [comment]
Again checking my plugins, and as a short reminder to release a new tag.

**Comment by jamessan** [comment]
Yes, I'll try to wrap up my changes for the next release soon.  I'd like to get it out sooner rather than later, especially due to the GnuPG 2.1 compatibility.

**Comment by wikimatze** [comment]
Wow, 2.1 is already out? I I still have the classic portable version 1.4.16 on my pc, think it's still on my xubuntu 14.04 machine.

**Comment by jamessan** [comment]
On Debian/Ubuntu, the 2.x series is packaged as gnupg2.

**Comment by wikimatze** [comment]
Installed it and how now `gpg2` on my machine. As soon as you are ready with your plugin, I can switch to it? Do I have to change my old gpg key then and/or my existing encrypted notes?

**Comment by jamessan** [comment]
You won't have to change anything to do with your key.  It's still gnupg, just a newer version which Debian hasn't made default yet.  If you want the plugin to use it, you'll need to let `g:GPGExecutable` appropriately.

**Comment by wikimatze** [comment]
What about now about a new release?

**Comment by danielcotton** [comment]
I'm sure a new release will be made when it's ready. No need to continue 
bothering James about it.

**Comment by wikimatze** [comment]
Yeah, I find the master pretty stable (using it for over one month now).

**Comment by jamessan** [comment]
2.6 was released in April.

**Comment by wikimatze** [comment]
Thank you very much.
