### ISSUE TITLE
Workaround in `s:GPGPostCmd()` has sideefects

### ISSUE THREAD

**Issue by mkoskar** [jamessan/vim-gnupg#28]
In my `.vimrc` I do meta mappings setup (`exec 'set <M-'.c.">=\e".c`). When I open `*.gpg` file so that `vim-gnupg` kicks in, those are reset. I figured out that problem is caused by supposed workaround for some other issue reading:

```
" Workaround a bug in the interaction between console vim and
" pinentry-curses by forcing Vim to re-detect and setup its terminal
" settings
let &term = &term
```

By commenting it out I get desired behaviour.

**Comment by jamessan** [comment]
I dislike the hack, but it is needed to allow things like you're trying to use after pinentry is run.  I think if you push your mappings into a function and do

    au TermChanged * call SetupMetaMaps()

you should be back in business.

**Comment by mkoskar** [comment]
I didn't know about `TermChanged`. I re-factored my code to use it. It works but not with `vim-gnugpg`.
With some simple debugging it seems that `TermChanged` is not triggered there.

My test case:

`autocmd TermChanged * echomsg 'term-changed'`

1) open fresh Vim
2) `:let &term = &tem`
3) `:messages` - verify that there is 1 `term-changed` message as expected
4) `:vnew test.gpg`
5) `:messages` - no additions here, but one would expect some
6) `:let &term = &term` - and this is strange as it would generate 3 messages

**Comment by jamessan** [comment]
It wasn't working because the TermChanged event was being emitted from within the BufReadCmd autocmd.  By default, autocmds aren't nested and you shouldn't need to make it nested.  I've added an explicit trigger of TermChanged to gnupg.vim which will resolve this.

**Comment by mkoskar** [comment]
It works now. Thanks! ;)
