### ISSUE TITLE
shelltemp is supported on Windows

### ISSUE THREAD

**Issue by heaths** [jamessan/vim-gnupg#29]
There's a comment in gnupg.vim that reads,

    noshelltemp isn't currently supported on Windows

But vim help for `shelltemp` shows,

    Currently a pipe is only supported on Unix and MS-Windows 2K and later.  You can check it with:
        :if has("filterpipe")

I do see that `shelltemp` is set but don't fully understand why procmon shows that a temp file is always created anyway (I do have `g:GPGUsePipes = 1`). I was interested in this plugin because I have an SSD and can't easily wipe secure temp files like an HDD (you have to multi-pass wipe the entire drive's free space on an SSD).

I'm happy to fix and submit a PR but not understanding this fully and hoping maybe you can shed light on it. Since `shelltemp` is set regardless of the platform, shouldn't this work without creating temp files at all? Or are the temp files containing something else that is not the decrypted contents?

**Comment by heaths** [comment]
I debugged vim and verified that on Windows the decrypted contents are being saved twice - once on decrypt and again on encrypt. This is bad on SSDs.

**Comment by jamessan** [comment]
If `'noshelltemp'` is set and Vim is still writing data to temp files, then that seems like a bug in Vim.  I'll try to get some time to debug that in the next few days.

**Comment by jamessan** [comment]
Ok, I did some debugging and the temp files that get created are from the places where the plugin calls `system()`.  There is no decrypted material involved in those cases.  They're information gathering commands -- GPG version, encryption type, recipients, and name/email <-> id conversion.

**Comment by heaths** [comment]
There is definitely decrypted information leaked to files. I set a breakpoint on `vim!GetTempFileNameA` and `vim!DeleteFileA` and verified it. The problem seems to be the check in gnupg.vim for `has('unix')`.

**Comment by jamessan** [comment]
I just stepped through again and checked every temp file that gets created and don't ever see anything other than stderr from gpg or the encrypted file contents.  Are you sure you have `let g:GPGUsePipes=1` and you don't have some other plugin that's writing out the buffer contents?

**Comment by heaths** [comment]
`g:GPGUsePipes=1`, yes. I'll double check other extensions but apart from that it's just what is documented to support omnisharp-vim.
