### ISSUE TITLE
E331: Must not add menu items directly to menu bar

### ISSUE THREAD

**Issue by ItsEric** [jamessan/vim-gnupg#39]
Hi,

Every time I want to open a .gpg file  get an error saying "E331: Must not add menu items directly to menu bar". I then have to press the Enter Key and enter my passphrase and then everything seems to work normally.

Does it breaks the security ?

Also is it safe to store a gpg-encrypted file in my dropbox folder and edit it from there or will uncrypted files will be saved during the editing process (using the vim-gnupg plugin of course) ?

I run Debian on a VM

Thanks !

**Comment by jamessan** [comment]
> Every time I want to open a .gpg file get an error saying "E331: Must not add menu items directly to menu bar". I then have to press the Enter Key and enter my passphrase and then everything seems to work normally.

I can't reproduce that behavior.  Even if I remove all menus before loading plugin/gnupg.vim, it works fine.  Can you post the output of `vim --version`?  Also, are you using a plugin manager to manage your plugins?  If so, can you post any of the plugin manager's commands that relate to vim-gnupg?

> Does it breaks the security ?

No.  The menu isn't necessary and doesn't have an effect on the security.

> Also is it safe to store a gpg-encrypted file in my dropbox folder and edit it from there or will uncrypted files will be saved during the editing process (using the vim-gnupg plugin of course) ?

It should be ok, but I don't know exactly how your environment is setup.  To know for sure, you could use something like `strace` to see what files Vim writes.

**Comment by ItsEric** [comment]
Thank you for your quick reply.

'#vim --version'
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 31 2015 23:36:03)
Rustines incluses : 1-488, 576

I am not using a plugin manager, I only have your plugin installed (the .vim file is located in my /root/.vim/plugin folder).

My Debian 8 installation is very recent and I haven't installed any package other than vim and some basic debian software (build-essential...). I don't think it matters at all but I use VMware fusion 7 on my Macbook pro to use Debian.

**Comment by jamessan** [comment]
That wasn't the full output of `vim --version`.  Can you please run `LANG=C vim --version` and post the entire output?  Thanks.

**Comment by ItsEric** [comment]
Sorry, I thought it was enough.

# LANG=C vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 31 2015 23:36:03)
Included patches: 1-488, 576
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by jamessan@debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       -python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux -lacl -lattr -lgpm -ldl

**Comment by jamessan** [comment]
I'm not able to reproduce this.  It doesn't make sense that this would only happen when you open a .gpg file since plugins are always loaded, and loading the plugin is what creates the menu.

Can you try with `vim -u NORC -N foo.gpg`?

**Comment by ItsEric** [comment]
My VM started crashing repeatedly in the last few days, I think something was misconfigured at the OS level and is responsible for my issues.

I am closing this issue as it appears not to be related to vim-gnupg.

Thank you for your support jamessan.
