### ISSUE TITLE
Breaks when 'shellslash' is on under Windows

### ISSUE THREAD

**Issue by BohrShaw** [jamessan/vim-gnupg#41]
It just breaks on various things when `set shellslash` while keeping other shell related options like 'shell' on their default.

The reason to `set shellslash` is simply for better User Experience like many tools on Windows do these days: Powershell, git, cygwin, etc. and popular Vim plugins like fugitive, unite, etc.

The effect of the option 'shellslash' is both internal and external. So we should check its value when invoking shell commands.

**Comment by jamessan** [comment]
I'll have to find some time to experiment with this on my Windows system.

**Comment by BohrShaw** [comment]
I had disabled 'shellslash' _again_ as it's been designed work with 'shell' like `cmd.exe` which I keep as the default. How I wish an option like 'internal_shellslash' is available!

Still glad to know you'll looking into this.

**Comment by jamessan** [comment]
I should have something to push out later today.
