### ISSUE TITLE
If a .asc file is edited and then saved, it is saved with out armor.

### ISSUE THREAD

**Issue by marklee77** [jamessan/vim-gnupg#42]
The problem is that, while GPGInit sets GPGOptions based on user preferences, these are cleared in GPGDecrypt. Armor is only turned on if gpg outputs "gpg: armor header", which the latest version on Ubuntu 14.04 does not do. This behaviour is wrong anyway, since a user might rename a .gpg to .asc and then edit, expecting it to change format, but it won't.

**Comment by jamessan** [comment]
> if gpg outputs "gpg: armor header", which the latest version on Ubuntu 14.04 does not do

As far as I can tell, it does still do this for armored files.  `LANG=C LC_ALL=C gpg --trust-model always --use-agent --verbose --decrypt --list-only --dry-run --no-use-agent filename` is the command that vim-gnupg runs, if you want to manually test.  That correctly reports for me with both 1.4.19 and 2.0.28.

> This behavior is wrong anyway, since a user might rename a .gpg to .asc and then edit, expecting it to change format, but it won't.

The filename is just a hint for initial behavior.  I'm not sure implicitly converting the format is a good idea.  The user can explicitly choose to armor with `:let g:GPGPreferArmor = 1` or running `:GPGEditOptions` and adding 'armor'.

**Comment by marklee77** [comment]
running GPGEditOptions after loading the file might work, but the script currently ignores the GPGPreferArmor setting for files that are being edited after GPGDecrypt.  Maybe there should be another setting, GPGForceArmor to force ascii armor even if the original file is binary?

The above command only outputs "gpg: public key is xxx" for me. I have 1.4.16 installed from the package gnupg-1.4.16-1ubuntu2.3.deb.

**Comment by jamessan** [comment]
> running GPGEditOptions after loading the file might work, but the script currently ignores the GPGPreferArmor setting for files that are being edited after GPGDecrypt

Yes, because `GPGPreferArmor` is only relevant for new files.  There's no reason for the plugin to change the armored state of an existing file just because it doesn't agree with what the extension is typically used for.

That being said, performing `:w foo.asc` when editing `foo.gpg` should honor `GPGPreferArmor` since it's creating a new file.  I'm doing some rework of how options are handled which should address this.

> The above command only outputs "gpg: public key is xxx" for me. I have 1.4.16 installed from the package gnupg-1.4.16-1ubuntu2.3.deb.

That's odd.  I wonder if that's a regression in 1.4.16 that's since been fixed.  The check for that string in the output is years old, from long before 1.4.16.

**Comment by marklee77** [comment]
Well, I couldn't find any command line options that might be affecting it (I even moved my gpg.conf to gpg.conf.bak) and I tried looking for a substring in the binary:

~~~
strings /usr/bin/gpg | grep armor | grep header
invalid armor header:
unknown armor header:
~~~

14.04 is the LTS release for Ubuntu, so if anyone has been having this problem then it will likely persist for a while unless vim-gnupg implements a workaround. I've patched my copy for the time being, though I understand your objection to mainlining it.

**Comment by jamessan** [comment]
`strings` doesn't show just `armor header` for me either, but it is in the source for 1.4.16.  Maybe the compiler optimizes it to just be a pointer into one of the other two strings.

```c
if( opt.verbose ) {
    log_info(_("armor header: "));
    print_string( stderr, line, len, 0 );
    putc('\n', stderr);
}
```

Are you sure you included the `--verbose` and that the file is actually armored?

**Comment by marklee77** [comment]
Okay, I figured it out. The files are definitely in ascii armor format, but at some point in the past I put "no-emit-version" in my ~/.gnupg/gpg.conf file, and this option apparently strips the armor header as well as the gpg version from the encrypted file. So, the problem is in my configuration and probably won't affect most people. Still, it seems like there should be some other way to determine unambiguously whether or not a given file is armored.

**Comment by jamessan** [comment]
Interesting.  Thanks for the info.  That should help me see if there's a better way to detect whether the file is armored.

**Comment by marklee77** [comment]
So, looking at the RFC for OpenPGP, it seems like the armor headers are the textual headers that appear after the "---- BEGIN PGP MESSAGE-----" line. They aren't required, and aren't protected from tampering by cryptographic signature or anything like that: https://tools.ietf.org/html/rfc4880#section-6.2

It does seem funny that gnupg doesn't have an option to just tell you whether a message is armored or binary, but gnupg is pretty idiosyncratic.

**Comment by sebcode** [comment]
This happens for me too. `.asc` files are always saved without armor. My gpg version does not  print that `armor header: ...` line. My `gnupg.conf` is empty. I'm on macOS using homebrew's gnupg. I've been using vim-gnupg for years and until recently it worked fine, not sure what changed.

```
$ strings /usr/local/bin/gpg | grep armor | grep header
invalid armor header:
armor header:
unknown armor header:

$ gpg --verbose --decrypt --list-only test.asc
gpg: public key is ...

$ head -n1 test.asc
-----BEGIN PGP MESSAGE-----

$ gpg --version
gpg (GnuPG) 2.1.21
libgcrypt 1.7.7
```

**Comment by jamessan** [comment]
@sebcode For some reason, your gpg configuration isn't adding an armor headers to the file.  Although it's pretty common for there to be armor headers, it's not a required part of the encoding.  I've opened #82 to track fixing this.

**Comment by sebcode** [comment]
Right that's it. Seems like the new default: (https://www.gnupg.org/download/release_notes.html)

> GnuPG 2.1.15 released (2016-08-18)
> gpg: Avoid publishing the GnuPG version by default with –armor.

Workaround: `emit-version` in `gpg.conf`. Seems to work fine now. Thanks for the hint.

**Comment by xizhendu** [comment]
Thank you!
I resolved the same issue by your tips.
