### ISSUE TITLE
Cannot decrypt on Windows 8.1 

### ISSUE THREAD

**Issue by DavBE** [jamessan/vim-gnupg#45]
Hello,

I am able to encrypt files but I cannot decrypt them once encrypted.

I think the issue is related to the language gpg is running.

From the plugin, line 385 :

let asymmPattern = 'gpg: public key is ' . s:keyPattern

My gpg is running in french, so the output of the command is not what the plugin expects.

I would be glad to run gpg in english but I can't find a way to do so.

Anyone had the issue and knows a workaround ?

Thanks,

David

**Comment by DavBE** [comment]
I've found a workaround and I'm posting this in case it may be useful to seomeone.

You have to find the directory in which translation are located, on my system it was :

C:\Program Files (x86)\GNU\GnuPG\share\locale

Now just rename the directory containing the translation for yout language (mine was fr, I renamed it to fr.old).

Regards,

David

**Comment by jamessan** [comment]
On non-Windows systems, `LANG=C LC_ALL=C` is prepended to the gpg commands to avoid that problem.  Looks like something similar needs to happen for Windows.

Can you post what the Vim command `:lang` reports?

**Comment by DavBE** [comment]
Here :

Current language: "LC_COLLATE=French_Belgium.1252;LC_CTYPE=C;LC_MONETARY=French_Belgium.1252;LC_NUMERIC=C;LC_TIME=French_Belgium.1252"

**Comment by jamessan** [comment]
Can you try this to see if it makes decryption work?

1. Rename the translation directory back to `fr`
2. Start Vim
3. Run `:lang messages C`
4. Open an encrypted file

**Comment by DavBE** [comment]
Yes it does work.

**Comment by jamessan** [comment]
And just to be sure, if you leave out step 3 then you encounter the failure?

**Comment by DavBE** [comment]
Indeed, leaving out step 3 makes it fail to decrypt.

**Comment by jamessan** [comment]
Ok, thanks.  I should have a fix pushed for this later today. :)

**Comment by DavBE** [comment]
Thank you. As a workaround I've been able to set the LANG environment variable to C

    C:\Users\david>echo %lang%
    C
    C:\Users\david>

I've just noticed I didn't mention I was running Windows...
