### ISSUE TITLE
throw-keyids breaks reading files that have been written with it enabled

### ISSUE THREAD

**Issue by atrull** [jamessan/vim-gnupg#50]
Hi

This isn't necessarily an improvement request, but rather something worth noting..

When throw-keyids is enabled you see the following:

Old files can be read, but any newly-saved with throw-keyids enabled, are no longer easily readable with the plugin.

throw-keyids is vaguely useful for securing privacy - see https://gist.github.com/bnagy/8914f712f689cc01c267

Could it be possible to specify a decryption key for the plugin ?

Anyway, there you go.

Cheers

Alex

**Comment by jamessan** [comment]
At least in my testing so far, I can easily open a file that was encrypted with `--throw-keyids`.  An unknown `0x00000000` is added to the set of recipients that will be encrypted to upon save.  That could be handled a little better by eliding any recipients whose key is all zeroes.
