### ISSUE TITLE
Explicitly name gpg2 as command for Fedora based systems?

### ISSUE THREAD

**Issue by afcowie** [jamessan/vim-gnupg#54]
It would seem in Fedora 23 we need to use `gpg2` as the command; the gnupg package is still providing _/usr/bin/gpg_. Is that configurable | hackable in the _gnupg.vim_ script?

**Comment by jamessan** [comment]
It's configurable via the `g:GPGExecutable` variable.  You can add

    let g:GPGExecutable = 'gpg2 --trust-model always'

to your vimrc to use gpg2 instead.

**Comment by afcowie** [comment]
Thanks! (I tried `set`, didn't realize `let` was the right command, hacked that line in script instead. This is much better).

**Comment by srstevenson** [comment]
@jamessan Would you entertain having vim-gnupg check for for `gpg2` first and if it's not found then falling back to `gpg`?

**Comment by avinash** [comment]
Hi. I also had the same issue with Fedora 25 and adding

`let g:GPGExecutable = 'gpg2 --trust-model always'`

in ~/.vimrc solved the issue. I would love to understand why gpg does not work anymore with the plugin given that it works very well on the command line itself...
