### ISSUE TITLE
.vimrc not sourced

### ISSUE THREAD

**Issue by louwers** [jamessan/vim-gnupg#58]
For some reason, my .vimrc is not sourced when I open .asc files using this plugin.
After disabling all other plugins and custom code, the problem persisted.

Any ideas on how I can identify the cause?

**Comment by jamessan** [comment]
What does `:scriptnames` show when you open an .asc file?

**Comment by louwers** [comment]
`~/.vimrc` is there. Session with .asc file:
```
  1: /etc/vimrc
  2: /usr/share/vim/vimfiles/archlinux.vim
  3: ~/.vimrc
  4: /usr/share/vim/vim74/ftoff.vim
  5: ~/dotfiles/.vim/bundle/Vundle.vim/autoload/vundle.vim
  6: ~/dotfiles/.vim/bundle/Vundle.vim/autoload/vundle/config.vim
  7: /usr/share/vim/vim74/filetype.vim
  8: /usr/share/vim/vimfiles/ftdetect/nginx.vim
  9: /usr/share/vim/vim74/ftplugin.vim
 10: /usr/share/vim/vim74/indent.vim
 11: /usr/share/vim/vim74/syntax/syntax.vim
 12: /usr/share/vim/vim74/syntax/synload.vim
 13: /usr/share/vim/vim74/syntax/syncolor.vim
 14: ~/dotfiles/.vim/colors/monokai.vim
 15: ~/dotfiles/.vim/bundle/vim-gnupg/plugin/gnupg.vim
 16: /usr/share/vim/vim74/plugin/getscriptPlugin.vim
 17: /usr/share/vim/vim74/plugin/gzip.vim
 18: /usr/share/vim/vim74/plugin/logiPat.vim
 19: /usr/share/vim/vim74/plugin/matchparen.vim
 20: /usr/share/vim/vim74/plugin/netrwPlugin.vim
 21: /usr/share/vim/vim74/plugin/rrhelper.vim
 22: /usr/share/vim/vim74/plugin/spellfile.vim
 23: /usr/share/vim/vim74/plugin/tarPlugin.vim
 24: /usr/share/vim/vim74/plugin/tohtml.vim
 25: /usr/share/vim/vim74/plugin/vimballPlugin.vim
 26: /usr/share/vim/vim74/plugin/zipPlugin.vim
 27: /usr/share/vim/vim74/scripts.vim
```
These additinal files seem to load with a normal session:
```
 27: /usr/share/vim/vim74/scripts.vim
 28: /usr/share/vim/vim74/ftplugin/vim.vim
 29: /usr/share/vim/vim74/indent/vim.vim
 30: /usr/share/vim/vim74/syntax/vim.vim
 31: /usr/share/vim/vim74/syntax/lua.vim
 32: /usr/share/vim/vim74/syntax/perl.vim
 33: /usr/share/vim/vim74/syntax/pod.vim
 34: /usr/share/vim/vim74/syntax/ruby.vim
 35: /usr/share/vim/vim74/syntax/python.vim
```

**Comment by jamessan** [comment]
Ok, so what's the actual problem you're experiencing?  Those latter files are loaded when you edit a `vim` filetype buffer, so that's not really relevant unless the .asc file is foo.vim.asc.

**Comment by louwers** [comment]
Thank you very much for your help @jamessan.

I mistakenly believed that none of my `.vimrc` loaded, but apparently it's just my colorscheme that fails to load... I'll figure it out.

Thanks again! Very useful plugin, enjoying it a lot.

**Comment by jamessan** [comment]
Well, your colorscheme was loaded:

> 14: ~/dotfiles/.vim/colors/monokai.vim

**Comment by louwers** [comment]
Yes, but my eyes are telling something different, it's weird!
```vim
autocmd User GnuPG :colorscheme monokai
```
actually 'solves' the problem. :laughing:

**Comment by jamessan** [comment]
Ooh, I might have an idea.  Are you manually setting `t_Co` in your vimrc?

**Comment by louwers** [comment]
I'm impressed! `monokai.vim` was.
I moved it to my `.vimrc`, because I need it if I ever want to change themes.

Is this a bug after all?

**Comment by jamessan** [comment]
Ugh, monokai shouldn't be doing that, but if it insists on doing so it should be done from a TermChanged autocmd.

The plugin has to re-set `'term'` due to other factors (described in #17), and this undoes what monokai is doing.  However, it's never a good idea to set that manually, anyway.  Your terminal should be advertising the correct `$TERM`, which may require configuration.

**Comment by louwers** [comment]
Gotcha! I set `TERM` and everything works. Much appreciated James.
[Pull request](https://github.com/sickill/vim-monokai/compare/master...louwers:patch-1) submitted :wink:
