### ISSUE TITLE
Workaround in 's:GPGPostCmd()' freezes vim in tmux-256color terminal

### ISSUE THREAD

**Issue by wimstefan** [jamessan/vim-gnupg#59]
Whenever I invoke vim in a tmux-256color terminal to edit a gnupg encrypted file it freezes, shows an empty window and does not react to any key press. I have to kill -KILL the process to get the terminal back.

Commenting out line 1363

``` viml
let &term = &term
```

resolves that problem but I'm not sure what other side-effects that might have ....

**Comment by jamessan** [comment]
If you have tmux use `screen-256color` for TERM instead, does that work?

Are you sure it's frozen?  Is there a child process that Vim is waiting on?

**Comment by wimstefan** [comment]
Yes screen-256color works. And perhaps "frozen" is the wrong expression - what happens is that after invoking the vim command I get an empty vim window with no information at all, it doesn't react to any key I tried (like <Esc>, <Ctrl-C>, ':q' or 'ZZ' and I have to kill the process ...

I've made some strace logfiles of such an attempt ... I can send you those via email if you're interested.

**Comment by jamessan** [comment]
You forgot to mention whether there are any child processes that Vim is waiting on.  Assuming you're on Linux, `ps afx` will show the process tree.

**Comment by wimstefan** [comment]
I apologize for forgetting to mention that. There are no child processes Vim is waiting on ...
(Checked with ```htop``` & ```ps afx```)

**Comment by jamessan** [comment]
Ok.  This seems like a Vim bug that this plugin just happens to bring out (not the first time).  If you send me the logfiles, I'll take a look.
