### ISSUE TITLE
refactor for clarity and faster loading

### ISSUE THREAD

**Issue by Konfekt** [jamessan/vim-gnupg#66]
Currently the whole plug-in resides in a single vim file. How about moving all autocmd's of the form 

``` vim
exe "autocmd BufReadCmd " . g:GPGFilePattern .  " call s:GPGInit(1) |" .
                                                \ " call s:GPGDecrypt(1)"
  exe "autocmd FileReadCmd " . g:GPGFilePattern . " call s:GPGInit(0) |" .
\ " call s:GPGDecrypt(0)"
```

to a `ftdetect/gpg.vim` file that defines a `gpg` filetype, along with a `ftplugin/gpg.vim` file?

Then the various script functions such as 

``` vim
function s:GPGEditRecipients()
```

go into a `autoload/gpg.vim` file and are named `gpg#EditRecipients()` and alike. This loads them only when called for.

**Comment by lucc** [comment]
Part of this is done in #52 you just have to wait for @jamessan to merge it or urge him to do so.

**Comment by Konfekt** [comment]
This Puts the functions into an autoload file. Should the Transfer of the filetype detection and plugin file go into a separate issue then ?

**Comment by lucc** [comment]
Yes (into a seperate PR).

As jamessan mentioned in #52 it will take some more time till #52 will be merged. But I think you can (now or then) build your transfer to the filetype folders on top of the PR #52. That way you don't have to redo the work and jamessan doesn't have to handle the "same" code changes twice.

**Comment by jamessan** [comment]
I agree with Bram's comment in vim/vim#1077 that there shouldn't be a filetype for this plugin.  The autocmds are fine in plugin/.

**Comment by Konfekt** [comment]
Ok. One might consider outsourcing them to ftdetect/.. and leave the filetype unchanged, but that's only to make the plugin/.. file leaner.

**Comment by jamessan** [comment]
Yeah, I'm not sure it's worth splitting them out.  They have to be loaded anyway and plugin/ files are automatically loaded.
