### ISSUE TITLE
Latest version does not honor -R argument to vim

### ISSUE THREAD

**Issue by mrplumber** [jamessan/vim-gnupg#67]
Hi,

I've noticed latest version ignores -R argument passed to vim (or alias 'view' on Debian). Wonder if that's by design now, or just a regression. I attached a file with uname -a and vim --version output on my system.
[system_info.txt](https://github.com/jamessan/vim-gnupg/files/437597/system_info.txt)

**Comment by jamessan** [comment]
Thanks for reporting this!
