### ISSUE TITLE
Symmetric encryption

### ISSUE THREAD

**Issue by hurlebouc** [jamessan/vim-gnupg#70]
Hello !
When I open a symmetrically encrypted file using this plugin, it asks me for the password: it's good. But when I want to write changes, I have to give again the password twice. Is there a way that makes the plug-in able to keep the same password all the time the file is open?

Thank you

**Comment by jamessan** [comment]
The plugin intentionally doesn't do any password handling.  That's all done by gpg.  Gpg prompts you twice because it wants to ensure you're typing the right password.
