### ISSUE TITLE
Edit recipients buffer is not shown on file open if custom GPGFilePattern is set

### ISSUE THREAD

**Issue by emilhuseynli** [jamessan/vim-gnupg#72]
Steps to reproduce:
1. add `let g:GPGFilePattern = '*.\(txt\)'` to .vimrc
2. open new file for edit 'vi new.txt'

Result: edit recipients buffer is not shown.

I think reason is that GPGFilePattern variable is not used everywhere, there are still places in plugin code where hardcoded `*.\(gpg\|asc\|pgp\)` is used instead of GPGFilePattern.

**Comment by ThomasAH** [comment]
This changeset introduces a bug: When opening test.gpg and using :GPGEditRecipients, vim opens one new (empty!) buffer named "GPGRecipients_test.gpg" and a second new buffer named "GPGRecipients_GPGRecipients_test.gpg" which contains the recipient list.

**Comment by jamessan** [comment]
Hmm, I tested that exact scenario.  Can you open a new issue about this and I'll look into it when I have access to my gpg setup?

**Comment by ThomasAH** [comment]
Filed as issue #75 with some further testing.
