### ISSUE TITLE
"set autowrite" causes "q!" to write plaintext gpg files to hard drive

### ISSUE THREAD

**Issue by rexroni** [jamessan/vim-gnupg#77]
Pretty much the title says the issue.  Steps to reproduce:

add `set autowrite` to `.vimrc`
run `vim test.gpg`, add some text and `:wq`
`cat test.gpg` will spit out gibberish
run `vim test.gpg`, modify some text and `:q!`
`cat test.gpg` will spit out your pre-":q!" buffer as plaintext

The writing of plaintext happens for new files as well (if you do `:q!`)

**Comment by jamessan** [comment]
Thanks for reporting this!  It should be fixed now.

**Comment by rexroni** [comment]
Thanks, that was fast!

**Comment by claes** [comment]
I think this defect motivates a new release.

**Comment by jamessan** [comment]
This wasn't actually present in the last release, but I am overdue for making a new release.
