### ISSUE TITLE
option to turn off gpg

### ISSUE THREAD

**Issue by akostadinov** [jamessan/vim-gnupg#78]
Hi, if I create a new file like `vi newfile.gpg`, then I try to save it, then I am asked for a password. If I just want to paste GPG encrypted content then this will double encrypt it.

There needs to be a option to turn off encryption when user desires.

**Comment by jamessan** [comment]
`:noau w` will save the buffer without running autocommands.

**Comment by akostadinov** [comment]
Thank you!
