### ISSUE TITLE
Unable to detect armored files without an armor header

### ISSUE THREAD

**Issue by jamessan** [jamessan/vim-gnupg#82]
The current detection for whether a file is armored relies on the presence of an armor header.  As described in [RFC 4880](https://tools.ietf.org/html/rfc4880#section-6.2), the armor headers are optional data so the plugin shouldn't rely on them for detection.

**Comment by chr4** [comment]
I've solved this using `head -n1` instead of `gpg --verbose [...]` - not sure if that has other implications, but it "works for me" (TM):

https://github.com/chr4/vim-gnupg/commit/b40d09e6fb83384686b77ba4ec89b97f8af28565

**Comment by tbabej** [comment]
Also experiencing this issue, fix above helped.

**Comment by jowagner** [comment]
@sebcode's workaround from issue #42 `echo emit-version >> ~/.gnupg/gpg.conf` may help people working with an old version of this plugin coming with their distro.
