### ISSUE TITLE
`:read` opens the file instead of reading its content

### ISSUE THREAD

**Issue by Neo-Oli** [jamessan/vim-gnupg#86]
If I open a file regular file and run `:read` to read in a gpg encrypted file, it reads in the content, but it also sets the file pointer to the encrypted file, so if I now save with  `:w` it will save to `test.gpg` instead of `test.txt`.

```
vi test.txt
:read test.gpg
:w
-> test.gpg written
```

**Comment by jamessan** [comment]
Thanks for the report!  This, and another `FileReadCmd` issue, should be fixed now.
