### ISSUE TITLE
Message could not be encrypted! (Press ENTER)

### ISSUE THREAD

**Issue by maasha** [jamessan/vim-gnupg#92]
After a recent update I can open encrypted files with vim but not save ...

**Comment by jamessan** [comment]
Update of the plugin or something else?

As far as debugging it:

* Start vim without any file argument
* `:let g:GPGDebugLevel=2` and `:let g:GPGDebugLog='gpg.log'`
* Open an encrypted file and save it
* Exit Vim

Then post the contents of `gpg.log` here.  There shouldn't be any sensitive information in it, but feel free to review and replace anything you don't want exposed with XXX or something.

**Comment by maasha** [comment]
Here goes:

```
GnuPG: gnupg.vim 2.5
GnuPG: command: LANG=C LC_ALL=C gpg --trust-model always --no-use-agent --version 2>/dev/null
GnuPG: output: gpg (GnuPG) 2.2.9^@libgcrypt 1.8.3^@Copyright (C) 2018 Free Software Foundation, Inc.^@License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>^@This is free software: you are free to change and redistribute it.^@There is NO WARRANTY, to the extent permitted by law.^@^@Home: /Users/maasha/.gnupg^@Supported algorithms:^@Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA^@Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,^@        CAMELLIA128, CAMELLIA192, CAMELLIA256^@Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224^@Compression: Uncompressed, ZIP, ZLIB, BZIP2^@
GnuPG: public key algorithms: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
GnuPG: cipher algorithms: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
GnuPG: hashing algorithms: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
GnuPG: compression algorithms: Uncompressed, ZIP, ZLIB, BZIP2
GnuPG: this file is symmetric encrypted
GnuPG: cipher-algo is AES256
GnuPG: decrypting file
GnuPG: command: silent r !LANG=C LC_ALL=C gpg --trust-model always --no-use-agent --quiet --decrypt '/Users/maasha/Google Drive/Privat/mine_koder.gpg' 2>/dev/null
GnuPG: called autocommand for mine_koder
GnuPG: called autocommand for mine_koder
GnuPG: encoding was "utf-8", switched to "utf-8"
GnuPG: recipients are: []
GnuPG: unknown recipients are: []
GnuPG: command: '[,']w !LANG=C LC_ALL=C gpg --trust-model always --no-use-agent --quiet --no-encrypt-to  --symmetric  --cipher-algo AES256  >'/var/folders/n8/bj0g9xds7b36585b25htych40000gp/T/vzeGX8T/3' 2>/dev/null
GnuPG: restored encoding "utf-8"
```

**Comment by maasha** [comment]
In the meantime I got it working using a generated pair of gpg keys, but ideally I don't want to be dependent on those.

**Comment by jamessan** [comment]
> GnuPG: gnupg.vim 2.5

The latest version is 2.6.1.  Can you try with that?

**Comment by maasha** [comment]
Right, so with the latest plugin I can save just OK!

However something baffles me:

1. I open a .gpg file and is prompted for password
2. I save and is prompted for password and confirmation
3. I reopen file and is not prompted for password - is that expected behaviour?

I notice that after step 3 a ~/.gnupg dir is created - perhaps with a key and a timer?

**Comment by jamessan** [comment]
See https://github.com/jamessan/vim-gnupg/issues/85#issuecomment-352837303.
