### ISSUE TITLE
Feature Request: Consider moving Command mappings to filetype map

### ISSUE THREAD

**Issue by fourjay** [jamessan/vim-gnupg#99]
I use Fugitive every day, and find myself typoing GP... in command-line tab completion. This in and of itself would not be a big deal if it did not also trigger vim-gnupg events.
I've worked around this by forking and creating a filetype in the auto-detect portion, then buffer mapping the GPGXXX commands there. I see that you generally do not like filetype mappings, as I understand it to keep syntax highlighting down to the original filetype (understandable). One possible workaround would be a composite mapping (``:set filetype=gpg.ORIG_FT``)

**Comment by jamessan** [comment]
I don't think filetypes are the right way to handle this, and there are other ways to workaround plugins/commands that have similar names.  I don't see anything being done in the plugin to handle this.
